server:
  port: 8888
  tomcat:
    max-connections: 500
    threads:
      max: 200
      min-spare: 20

spring:
  application:
    name: im-platform
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://im-mysql:3306/im_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: BoxIM@2024!Strong
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
    
  data:
    redis:
      host: im-redis
      port: 6379
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 5

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml
  type-aliases-package: com.bx.implatform.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# MinIO配置（需要替换为实际的云服务器IP）
minio:
  endpoint: http://im-minio:9000
  accessKey: minioadmin
  secretKey: BoxIMMinio@2024!
  bucketName: box-im

# WebSocket服务地址（需要替换为实际的云服务器公网IP）
ws:
  url: ws://YOUR_SERVER_IP:8878

# IM客户端配置
im:
  server:
    url: http://im-server:8878

# 日志配置
logging:
  level:
    root: INFO
    com.bx.implatform: INFO
  file:
    path: /app/logs
    name: /app/logs/im-platform.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
