server:
  port: 8878

netty:
  websocket:
    port: 8878
    path: /im
  private:
    port: 8879

spring:
  application:
    name: im-server
    
  data:
    redis:
      host: im-redis
      port: 6379
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 5

# 日志配置
logging:
  level:
    root: INFO
    com.bx.imserver: INFO
  file:
    path: /app/logs
    name: /app/logs/im-server.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
